name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Install Android SDK
        run: |
          sudo apt update
          sudo apt install -y openjdk-11-jdk-headless
          wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip -O cmdline-tools.zip
          unzip -qq -d $ANDROID_SDK_ROOT cmdline-tools.zip
          mv $ANDROID_SDK_ROOT/cmdline-tools $ANDROID_SDK_ROOT/tools
          echo "export PATH=$ANDROID_SDK_ROOT/tools/bin:$PATH" >> $GITHUB_ENV
          yes | sdkmanager --licenses
          sdkmanager "build-tools;29.0.3" "platforms;android-29" "platform-tools" "extras;google;m2repository" "extras;android;m2repository"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install Cython and Buildozer
        run: |
          python -m pip install --upgrade pip
          python -m pip install cython buildozer

      - name: Build APK
        run: buildozer android debug
