name: Build APK

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: quay.io/pypa/manylinux2014_x86_64  # Use a pre-built Docker container

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # Specify the Python version you're using

    - name: Install Buildozer
      run: |
        python -m pip install --upgrade pip
        python -m pip install buildozer

    - name: Build APK
      run: buildozer android debug
